Rails.application.routes.draw do
  root 'autotrader#index'
  get 'autotrader/buy'
  get 'autotrader/about'
  get 'autotrader/account'
  get 'autotrader/chat'
  get 'autotrader/contact'
  get 'autotrader/ebent'
  get 'autotrader/histry'
  get 'autotrader/map'
  get 'autotrader/payment'
  get 'autotrader/premium'
  get 'autotrader/profile1'
  get 'autotrader/profile2'
  get 'autotrader/profile3'
  get 'autotrader/profile4'
  get 'autotrader/sale'
  get 'autotrader/see'
  get 'autotrader/strategy'
  get 'autotrader/team'
  get 'autotrader/used'
  get 'autotrader/event'
  get 'autotrader/see'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
